#!/usr/bin/env perl

=head1 NAME

download_mlst_databases

=head1 SYNOPSIS

download_mlst_databases

=head1 DESCRIPTION

This script downloads all the MLST databases

=head1 CONTACT

path-help@sanger.ac.uk

=head1 METHODS

=cut
package ReferenceTrack;

BEGIN { unshift(@INC, './modules') }
use Moose;
use Getopt::Long;

use MLST::DatabaseSettings;
use MLST::Download::Databases;

my ($config_file, $base_directory, $help);

GetOptions ('c|config=s'         => \$config_file,
            'b|base_directory=s' => \$base_directory,
            'h|help'             => \$help,
);

(! $help)or die <<USAGE;
Usage: $0 [options]
Downloads all the MLST databases to disk

# download everything with defaults
download_mlst_databases

# XML file containing details of the MLST databases (from pubmlst)
download_mlst_databases -c my_config_file.json

# destination base directory defaults to /lustre/scratch108/pathogen/pathpipe/prokaryotes/mlst
download_mlst_databases -b /path/to/destination

USAGE
;

$config_file    ||= 'http://pubmlst.org/data/dbases.xml';
$base_directory ||= '/lustre/scratch108/pathogen/pathpipe/mlst';

my $database_settings = MLST::DatabaseSettings->new(filename => $config_file)->settings;
my $databases = MLST::Download::Databases->new(
  databases_attributes => $database_settings,
  base_directory  => $base_directory
);
$databases->update();
